profile: !ENV ${PROFILE}

selenium:
  page_load_seconds_timeout: 30

groceries_homepage:
  url: "https://www.target.com/c/grocery/-/N-5xt1a"
  categories_container: 
    css_selector: "[data-test='@web/slingshot-components/bubcat']"
    categories_button_appended_css_selector: " button"
    categories_element_appended_css_selector: " li"
    categories_name_container_appended_css_selector: " [data-test='bubcatItemTitleComponent'] span"
